"""Generate HydroTone's English, Korean, Japanese, Simplified and Traditional Chinese catalog."""
import json
from pathlib import Path

T = {
"1 photo export. This uses your free photo.": ("무료 사진 내보내기 1회입니다. 이번 내보내기에 무료 이용권을 사용합니다.", "写真を1枚無料で書き出せます。この書き出しで無料枠を使用します。", "可免费导出 1 张照片。本次导出将使用免费额度。", "可免費匯出 1 張照片。本次匯出將使用免費額度。"),
"1 video export · first 10 seconds · up to 1080p SDR. This uses your free video.": ("무료 동영상 내보내기 1회 · 처음 10초 · 최대 1080p SDR입니다. 이번 내보내기에 무료 이용권을 사용합니다.", "動画を1本無料で書き出せます · 冒頭10秒 · 最大1080p SDR。この書き出しで無料枠を使用します。", "可免费导出 1 个视频 · 前 10 秒 · 最高 1080p SDR。本次导出将使用免费额度。", "可免費匯出 1 部影片 · 前 10 秒 · 最高 1080p SDR。本次匯出將使用免費額度。"),
"4K export": ("4K 내보내기", "4K書き出し", "4K 导出", "4K 匯出"),
"All processing stays on your iPhone. No account or subscription.": ("모든 처리는 iPhone에서 이루어집니다. 계정이나 구독이 필요하지 않습니다.", "すべての処理はiPhone上で行われます。アカウントやサブスクリプションは不要です。", "所有处理都在 iPhone 上完成。无需账户或订阅。", "所有處理都在 iPhone 上完成。無需帳號或訂閱。"),
"Allow HydroTone to add to Photos in Settings, then try saving again.": ("설정에서 HydroTone이 사진에 추가하도록 허용한 후 다시 저장하세요.", "設定でHydroToneによる写真への追加を許可してから、もう一度保存してください。", "请在“设置”中允许 HydroTone 添加到照片，然后再次保存。", "請在「設定」中允許 HydroTone 加入照片，然後再次儲存。"),
"Bring back\nthe dive.": ("다이빙의 색을\n되찾으세요.", "ダイビングの色を\n取り戻そう。", "找回潜水时的\n真实色彩。", "找回潛水時的\n真實色彩。"),
"Buy Pro · %@": ("Pro 구매 · %@", "Proを購入 · %@", "购买 Pro · %@", "購買 Pro · %@"),
"Cancel": ("취소", "キャンセル", "取消", "取消"),
"Cancelled": ("취소됨", "キャンセルしました", "已取消", "已取消"),
"Checking your video…": ("동영상을 확인하는 중…", "ビデオを確認中…", "正在检查视频…", "正在檢查影片…"),
"Clear Water": ("맑은 물", "クリアウォーター", "清澈水域", "清澈水域"),
"Color": ("색상", "カラー", "色彩", "色彩"),
"Compare": ("비교", "比較", "对比", "比較"),
"Corrected": ("보정", "補正後", "校正后", "校正後"),
"Couldn’t finish": ("완료할 수 없음", "完了できませんでした", "无法完成", "無法完成"),
"Couldn’t import": ("가져올 수 없음", "読み込めませんでした", "无法导入", "無法匯入"),
"Couldn’t prepare diagnostics. Please try again.": ("진단 정보를 준비할 수 없습니다. 다시 시도하세요.", "診断情報を準備できませんでした。もう一度お試しください。", "无法准备诊断信息。请重试。", "無法準備診斷資訊。請再試一次。"),
"Couldn’t save": ("저장할 수 없음", "保存できませんでした", "无法保存", "無法儲存"),
"Deep Dive": ("딥 다이브", "ディープダイブ", "深潜", "深潛"),
"Delete local diagnostics": ("로컬 진단 정보 삭제", "ローカル診断情報を削除", "删除本地诊断信息", "刪除本機診斷資訊"),
"Diagnostics": ("진단", "診断", "诊断", "診斷"),
"Diagnostics stay on this iPhone. Nothing is sent automatically.": ("진단 정보는 이 iPhone에만 저장됩니다. 자동으로 전송되는 정보는 없습니다.", "診断情報はこのiPhone内に保存されます。自動送信は行いません。", "诊断信息仅保存在此 iPhone 上，不会自动发送。", "診斷資訊只會儲存在此 iPhone，不會自動傳送。"),
"Discard export": ("내보낸 파일 삭제", "書き出したファイルを削除", "删除导出文件", "刪除匯出檔案"),
"Done": ("완료", "完了", "完成", "完成"),
"Edit": ("편집", "編集", "编辑", "編輯"),
"Export": ("내보내기", "書き出す", "导出", "匯出"),
"Export cancelled": ("내보내기가 취소되었습니다", "書き出しをキャンセルしました", "导出已取消", "匯出已取消"),
"Export cancelled because HydroTone went into the background. Keep the app open and try again. Your trial hasn’t been used.": ("HydroTone이 백그라운드로 전환되어 내보내기가 취소되었습니다. 앱을 열어 둔 채 다시 시도하세요. 무료 이용권은 차감되지 않았습니다.", "HydroToneがバックグラウンドに移ったため、書き出しをキャンセルしました。アプリを開いたまま、もう一度お試しください。無料枠は使用されていません。", "HydroTone 进入后台，因此导出已取消。请保持应用打开后重试。免费额度未被使用。", "HydroTone 進入背景，因此匯出已取消。請保持 App 開啟後再試一次。免費額度未被使用。"),
"Export complete": ("내보내기 완료", "書き出し完了", "导出完成", "匯出完成"),
"Exporting %lld%%": ("내보내는 중 %lld%%", "書き出し中 %lld%%", "正在导出 %lld%%", "正在匯出 %lld%%"),
"Exporting…": ("내보내는 중…", "書き出し中…", "正在导出…", "正在匯出…"),
"Failed or cancelled exports don’t use your trial.": ("실패하거나 취소된 내보내기는 무료 이용권을 차감하지 않습니다.", "失敗またはキャンセルした書き出しでは無料枠を使用しません。", "导出失败或取消不会消耗免费额度。", "匯出失敗或取消不會使用免費額度。"),
"Filter intensity": ("필터 강도", "フィルターの強度", "滤镜强度", "濾鏡強度"),
"For a crash, TestFlight and Xcode Organizer may provide a separate Apple crash report. Keep the app build and its debug symbols together.": ("충돌이 발생하면 TestFlight와 Xcode Organizer에서 Apple 충돌 보고서를 별도로 확인할 수 있습니다. 앱 빌드와 디버그 심볼을 함께 보관하세요.", "クラッシュについては、TestFlightとXcode OrganizerからAppleのクラッシュレポートを別途取得できる場合があります。アプリのビルドとデバッグシンボルを一緒に保管してください。", "发生崩溃时，TestFlight 和 Xcode Organizer 可能会提供单独的 Apple 崩溃报告。请一并保留应用构建和调试符号。", "發生當機時，TestFlight 與 Xcode Organizer 可能會提供個別的 Apple 當機報告。請一併保留 App 版本與偵錯符號。"),
"Free trial": ("무료 이용", "無料体験", "免费试用", "免費試用"),
"Full-length video exports": ("전체 길이 동영상 내보내기", "フル尺ビデオの書き出し", "完整视频导出", "完整影片匯出"),
"Get Pro": ("Pro 구매", "Proを入手", "获取 Pro", "取得 Pro"),
"HDR export is unavailable for this media/device. You can export SDR.": ("이 미디어 또는 기기에서는 HDR 내보내기를 사용할 수 없습니다. SDR로 내보낼 수 있습니다.", "このメディアまたはデバイスではHDR書き出しを利用できません。SDRで書き出せます。", "此媒体或设备无法导出 HDR。你可以导出 SDR。", "此媒體或裝置無法匯出 HDR。你可以匯出 SDR。"),
"HDR export requires a supported iPhone. SDR export is available in the simulator.": ("HDR 내보내기에는 지원되는 iPhone이 필요합니다. 시뮬레이터에서는 SDR 내보내기를 사용할 수 있습니다.", "HDR書き出しには対応するiPhoneが必要です。シミュレータではSDR書き出しを利用できます。", "HDR 导出需要受支持的 iPhone。模拟器中可导出 SDR。", "HDR 匯出需要支援的 iPhone。模擬器中可匯出 SDR。"),
"HDR export where supported": ("지원되는 경우 HDR 내보내기", "対応環境でのHDR書き出し", "支持时导出 HDR", "支援時匯出 HDR"),
"HDR photo export is unavailable. Your photo will be saved as a wide-color SDR JPEG.": ("HDR 사진 내보내기는 사용할 수 없습니다. 사진은 광색역 SDR JPEG로 저장됩니다.", "HDR写真の書き出しは利用できません。写真は広色域SDR JPEGとして保存されます。", "无法导出 HDR 照片。照片将保存为广色域 SDR JPEG。", "無法匯出 HDR 照片。照片將儲存為廣色域 SDR JPEG。"),
"HDR source · SDR preview": ("HDR 원본 · SDR 미리보기", "HDRソース · SDRプレビュー", "HDR 源 · SDR 预览", "HDR 來源 · SDR 預覽"),
"HDR · HEVC · 10-bit. The editor shows a tone-mapped SDR preview.": ("HDR · HEVC · 10비트. 편집기에는 톤 매핑된 SDR 미리보기가 표시됩니다.", "HDR · HEVC · 10ビット。エディタにはトーンマップされたSDRプレビューが表示されます。", "HDR · HEVC · 10 位。编辑器显示色调映射后的 SDR 预览。", "HDR · HEVC · 10 位元。編輯器顯示色調映射後的 SDR 預覽。"),
"HydroTone Pro": ("HydroTone Pro", "HydroTone Pro", "HydroTone Pro", "HydroTone Pro"),
"HydroTone Pro is unlocked.": ("HydroTone Pro가 잠금 해제되었습니다.", "HydroTone Proが利用可能になりました。", "HydroTone Pro 已解锁。", "HydroTone Pro 已解鎖。"),
"Importing…": ("가져오는 중…", "読み込み中…", "正在导入…", "正在匯入…"),
"Intensity": ("강도", "強度", "强度", "強度"),
"Keep HydroTone open until export finishes.": ("내보내기가 끝날 때까지 HydroTone을 열어 두세요.", "書き出しが完了するまでHydroToneを開いたままにしてください。", "导出完成前请保持 HydroTone 打开。", "匯出完成前請保持 HydroTone 開啟。"),
"Memory is low. Try a smaller photo or a lower video resolution.": ("메모리가 부족합니다. 더 작은 사진이나 낮은 동영상 해상도를 사용해 보세요.", "メモリが不足しています。小さい写真または低いビデオ解像度でお試しください。", "内存不足。请尝试较小的照片或较低的视频分辨率。", "記憶體不足。請嘗試較小的照片或較低的影片解析度。"),
"Natural Dive": ("내추럴 다이브", "ナチュラルダイブ", "自然潜水", "自然潛水"),
"Natural color for your underwater photos and videos.": ("수중 사진과 동영상에 자연스러운 색을 되찾아 줍니다.", "水中の写真やビデオに自然な色を取り戻します。", "为水下照片和视频还原自然色彩。", "為水下照片與影片還原自然色彩。"),
"No HydroTone Pro purchase was found for this Apple Account.": ("이 Apple 계정에서 HydroTone Pro 구매 내역을 찾지 못했습니다.", "このApple AccountにはHydroTone Proの購入履歴がありません。", "未找到此 Apple 账户购买 HydroTone Pro 的记录。", "找不到此 Apple 帳號購買 HydroTone Pro 的記錄。"),
"OK": ("확인", "OK", "好", "好"),
"One-time purchase. Every dive.": ("한 번 구매로 모든 다이빙에 사용하세요.", "買い切りで、すべてのダイビングに。", "一次购买，每次潜水都能用。", "一次購買，每次潛水都能用。"),
"Opening…": ("여는 중…", "開いています…", "正在打开…", "正在開啟…"),
"Original": ("원본", "オリジナル", "原始", "原始"),
"Original resolution": ("원본 해상도", "元の解像度", "原始分辨率", "原始解析度"),
"Original resolution · SDR · JPEG": ("원본 해상도 · SDR · JPEG", "元の解像度 · SDR · JPEG", "原始分辨率 · SDR · JPEG", "原始解析度 · SDR · JPEG"),
"Photo preview": ("사진 미리보기", "写真プレビュー", "照片预览", "照片預覽"),
"Prepare diagnostic report": ("진단 보고서 준비", "診断レポートを準備", "准备诊断报告", "準備診斷報告"),
"Pro is unlocked": ("Pro 잠금 해제됨", "Pro利用可能", "Pro 已解锁", "Pro 已解鎖"),
"Purchase is currently unavailable.": ("현재 구매를 이용할 수 없습니다.", "現在購入できません。", "目前无法购买。", "目前無法購買。"),
"Purchase restored.": ("구매가 복원되었습니다.", "購入を復元しました。", "购买已恢复。", "購買已回復。"),
"Ready to save": ("저장 준비 완료", "保存の準備ができました", "可以保存了", "可以儲存了"),
"Resolution": ("해상도", "解像度", "分辨率", "解析度"),
"Restore Purchase": ("구매 복원", "購入を復元", "恢复购买", "回復購買"),
"Restore Red": ("붉은색 복원", "赤色を復元", "恢复红色", "恢復紅色"),
"Retry": ("다시 시도", "再試行", "重试", "再試一次"),
"Retry preview": ("미리보기 다시 시도", "プレビューを再試行", "重试预览", "重試預覽"),
"Save to Photos": ("사진에 저장", "写真に保存", "保存到照片", "儲存到照片"),
"Saved to Photos": ("사진에 저장되었습니다", "写真に保存しました", "已保存到照片", "已儲存到照片"),
"Saving…": ("저장하는 중…", "保存中…", "正在保存…", "正在儲存…"),
"Select Photo": ("사진 선택", "写真を選択", "选择照片", "選擇照片"),
"Select Video": ("동영상 선택", "ビデオを選択", "选择视频", "選擇影片"),
"Share diagnostic report": ("진단 보고서 공유", "診断レポートを共有", "共享诊断报告", "分享診斷報告"),
"Show original media without correction": ("보정하지 않은 원본 미디어 표시", "補正前のオリジナルを表示", "显示未经校正的原始媒体", "顯示未經校正的原始媒體"),
"The App Store couldn’t complete this request. Check your connection and try again.": ("App Store에서 요청을 완료할 수 없습니다. 연결을 확인하고 다시 시도하세요.", "App Storeでリクエストを完了できませんでした。接続を確認してもう一度お試しください。", "App Store 无法完成此请求。请检查网络连接后重试。", "App Store 無法完成此要求。請檢查網路連線後再試一次。"),
"The export couldn’t finish. Please try again.": ("내보내기를 완료할 수 없습니다. 다시 시도하세요.", "書き出しを完了できませんでした。もう一度お試しください。", "无法完成导出。请重试。", "無法完成匯出。請再試一次。"),
"The exported file didn’t pass our quality checks. Nothing was saved.": ("내보낸 파일이 품질 검사를 통과하지 못해 저장되지 않았습니다.", "書き出したファイルが品質チェックに合格しなかったため、保存されませんでした。", "导出文件未通过质量检查，因此未保存。", "匯出檔案未通過品質檢查，因此未儲存。"),
"The media service is temporarily busy. Wait a moment and try again.": ("미디어 서비스가 일시적으로 사용 중입니다. 잠시 후 다시 시도하세요.", "メディアサービスが一時的にビジーです。しばらくしてからもう一度お試しください。", "媒体服务暂时繁忙。请稍后重试。", "媒體服務暫時忙碌。請稍後再試一次。"),
"The purchase couldn’t finish. Please try again.": ("구매를 완료할 수 없습니다. 다시 시도하세요.", "購入を完了できませんでした。もう一度お試しください。", "无法完成购买。请重试。", "無法完成購買。請再試一次。"),
"The purchase is currently unavailable. Please try again later.": ("현재 구매를 이용할 수 없습니다. 나중에 다시 시도하세요.", "現在購入できません。しばらくしてからもう一度お試しください。", "目前无法购买。请稍后重试。", "目前無法購買。請稍後再試一次。"),
"The report includes error codes and Apple performance diagnostics, which may contain approximate times and device, OS and app details. It excludes your photos, videos, filenames and location.": ("보고서에는 오류 코드와 Apple 성능 진단 정보가 포함되며 대략적인 시간, 기기, OS, 앱 정보가 들어갈 수 있습니다. 사진, 동영상, 파일 이름, 위치는 포함되지 않습니다.", "レポートにはエラーコードとAppleのパフォーマンス診断が含まれ、おおよその時刻、デバイス、OS、アプリの情報が含まれる場合があります。写真、ビデオ、ファイル名、位置情報は含まれません。", "报告包含错误代码和 Apple 性能诊断，可能包含大致时间、设备、系统和应用信息。不会包含照片、视频、文件名或位置。", "報告包含錯誤代碼與 Apple 效能診斷，可能包含大約時間、裝置、系統與 App 資訊。不會包含照片、影片、檔名或位置。"),
"There isn’t enough free storage. Free up some space and try again.": ("저장 공간이 부족합니다. 공간을 확보한 후 다시 시도하세요.", "空き容量が不足しています。容量を確保してからもう一度お試しください。", "可用存储空间不足。请释放一些空间后重试。", "可用儲存空間不足。請釋放一些空間後再試一次。"),
"This item may need to download from iCloud. Check your connection and try again.": ("이 항목은 iCloud에서 다운로드해야 할 수 있습니다. 연결을 확인하고 다시 시도하세요.", "この項目はiCloudからのダウンロードが必要な場合があります。接続を確認してもう一度お試しください。", "此项目可能需要从 iCloud 下载。请检查网络连接后重试。", "此項目可能需要從 iCloud 下載。請檢查網路連線後再試一次。"),
"This media couldn’t be opened. Try another photo or video.": ("이 미디어를 열 수 없습니다. 다른 사진이나 동영상을 사용해 보세요.", "このメディアを開けませんでした。別の写真またはビデオをお試しください。", "无法打开此媒体。请尝试其他照片或视频。", "無法開啟此媒體。請嘗試其他照片或影片。"),
"This media format isn’t supported on this device.": ("이 기기에서는 해당 미디어 형식을 지원하지 않습니다.", "このデバイスではこのメディア形式に対応していません。", "此设备不支持该媒体格式。", "此裝置不支援此媒體格式。"),
"This video is SDR. HDR export requires HDR source footage.": ("이 동영상은 SDR입니다. HDR 내보내기에는 HDR 원본이 필요합니다.", "このビデオはSDRです。HDR書き出しにはHDRソースが必要です。", "此视频为 SDR。HDR 导出需要 HDR 源素材。", "此影片為 SDR。HDR 匯出需要 HDR 來源素材。"),
"This video’s HDR format cannot be safely exported as HDR.": ("이 동영상의 HDR 형식은 HDR로 안전하게 내보낼 수 없습니다.", "このビデオのHDR形式は安全にHDR書き出しできません。", "无法将此视频的 HDR 格式安全导出为 HDR。", "無法將此影片的 HDR 格式安全匯出為 HDR。"),
"Trial access couldn’t be checked securely. Please try again.": ("무료 이용 상태를 안전하게 확인할 수 없습니다. 다시 시도하세요.", "無料体験の状態を安全に確認できませんでした。もう一度お試しください。", "无法安全检查试用状态。请重试。", "無法安全檢查試用狀態。請再試一次。"),
"Trial access couldn’t be checked securely. Unlock your iPhone and try again.": ("무료 이용 상태를 안전하게 확인할 수 없습니다. iPhone의 잠금을 해제하고 다시 시도하세요.", "無料体験の状態を安全に確認できませんでした。iPhoneのロックを解除してもう一度お試しください。", "无法安全检查试用状态。请解锁 iPhone 后重试。", "無法安全檢查試用狀態。請解鎖 iPhone 後再試一次。"),
"Tropical": ("트로피컬", "トロピカル", "热带", "熱帶"),
"Unlimited photo exports": ("사진 무제한 내보내기", "写真を無制限に書き出し", "无限导出照片", "無限匯出照片"),
"Wide color is preserved. HDR photo export is unavailable.": ("광색역은 유지됩니다. HDR 사진 내보내기는 사용할 수 없습니다.", "広色域は保持されます。HDR写真の書き出しは利用できません。", "保留广色域。无法导出 HDR 照片。", "保留廣色域。無法匯出 HDR 照片。"),
"Your export has been checked and is ready for Photos.": ("내보낸 파일을 확인했습니다. 사진에 저장할 준비가 되었습니다.", "書き出したファイルを確認しました。写真への保存準備ができました。", "导出文件已检查，可以保存到照片。", "匯出檔案已檢查，可以儲存到照片。"),
"Your iPhone needs to cool down before exporting. Wait a moment and try again.": ("내보내기 전에 iPhone을 식혀야 합니다. 잠시 후 다시 시도하세요.", "書き出す前にiPhoneを冷ます必要があります。しばらくしてからもう一度お試しください。", "iPhone 需要冷却后才能导出。请稍后重试。", "iPhone 需要冷卻後才能匯出。請稍後再試一次。"),
"Your media stays on your iPhone.": ("미디어는 iPhone 밖으로 전송되지 않습니다.", "メディアはiPhoneの外部に送信されません。", "媒体始终保留在你的 iPhone 上。", "媒體始終保留在你的 iPhone 上。"),
"Your purchase couldn’t be verified. Please try Restore Purchase.": ("구매를 확인할 수 없습니다. 구매 복원을 시도하세요.", "購入を確認できませんでした。「購入を復元」をお試しください。", "无法验证购买。请尝试“恢复购买”。", "無法驗證購買。請嘗試「回復購買」。"),
"Your purchase is being verified. Try Restore Purchase shortly.": ("구매를 확인하는 중입니다. 잠시 후 구매 복원을 시도하세요.", "購入を確認中です。しばらくしてから「購入を復元」をお試しください。", "正在验证购买。请稍后尝试“恢复购买”。", "正在驗證購買。請稍後嘗試「回復購買」。"),
"Your purchase is pending approval. Pro will unlock when it’s approved.": ("구매 승인을 기다리는 중입니다. 승인되면 Pro가 잠금 해제됩니다.", "購入は承認待ちです。承認されるとProが利用可能になります。", "购买正在等待批准。批准后将解锁 Pro。", "購買正在等待核准。核准後將解鎖 Pro。"),
}

# Short, unambiguous interface terms and technical labels.
T.update({
"1080p": ("1080p", "1080p", "1080p", "1080p"), "HDR": ("HDR", "HDR", "HDR", "HDR"), "SDR": ("SDR", "SDR", "SDR", "SDR"),
"Color": ("색상", "カラー", "色彩", "色彩"), "Deep Dive": ("딥 다이브", "ディープダイブ", "深潜", "深潛"),
})

locales = ["ko", "ja", "zh-Hans", "zh-Hant"]
strings = {}
for key, translations in sorted(T.items()):
    localized = {"en": {"stringUnit": {"state": "translated", "value": key}}}
    for locale, value in zip(locales, translations):
        localized[locale] = {"stringUnit": {"state": "translated", "value": value}}
    strings[key] = {"extractionState": "manual", "localizations": localized}

Path("HydroTone/Resources/Localizable.xcstrings").write_text(
    json.dumps({"sourceLanguage": "en", "strings": strings, "version": "1.0"}, ensure_ascii=False, indent=2) + "\n"
)
